Repository SU-SOE/soe_basic, pull requests merged in 2020-11, with the labels that each got.

#44 "8.x-1.x 8.1.4
  CHANGELOG.md
  dist/css/theme.css
  soe_basic.info.yml
  src/scss/theme/_events.scss
  templates/sections/header-full-width.html.twig
Labels: patch

#46 D8CORE-2670: Styles for external links
  dist/css/base.css
  dist/css/theme.css
  src/scss/theme/_button.scss
  src/scss/theme/_people.scss
  src/scss/utilities/mixins/_links.scss
Labels: patch, size/s

#48 D8CORE-3004: Fixing the cards for Events and News to match
  dist/css/theme.css
  src/scss/theme/_events.scss
  src/scss/theme/_news.scss
Labels: size/xs
