Repository SU-SOE/soe_basic, pull requests merged in 2020-12, with the labels that each got.

#49 D8CORE-2964: updating the decanter version
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/media/media.twig
  package-lock.json
  package.json
Labels: size/xs

#50 "8.x-1.x 8.1.5
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/auto-label.json
  .github/pull_request_template.md
  .github/workflows/label.yml
  .github/workflows/release.yml
  CHANGELOG.md
  composer.json
  dist/css/base.css
  dist/css/components.css
  dist/css/theme.css
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/media/media.twig
  package-lock.json
  package.json
  soe_basic.info.yml
  src/scss/components/index.scss
  src/scss/components/lockup/_lockup.scss
  src/scss/components/lockup/index.scss
  src/scss/theme/_button.scss
  src/scss/theme/_events.scss
  src/scss/theme/_news.scss
  src/scss/theme/_people.scss
  src/scss/utilities/mixins/_links.scss
Labels: patch, size/s

#51 8.1.6
  composer.json
  soe_basic.info.yml
Labels: patch, size/xs
