Repository SU-SOE/soe_basic, pull requests merged in 2021-02, with the labels that each got.

#58 D8CORE-3486: Correcting people link colors and updated Decanter
  dist/css/base.css
  dist/css/theme.css
  package-lock.json
  package.json
  src/scss/theme/_people.scss
Labels: size/l

#60 "8.x-1.x 8.1.8
  CHANGELOG.md
  dist/css/base.css
  dist/css/theme.css
  package-lock.json
  package.json
  soe_basic.info.yml
  src/scss/theme/_background-classes.scss
  src/scss/theme/_events.scss
  src/scss/theme/_people.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_links.scss
Labels: patch, size/l

#59 D8CORE-3248: publication set up for SOE
  dist/css/base.css
  dist/css/theme.css
  package-lock.json
  src/scss/theme/_publications.scss
  src/scss/theme/index.scss
Labels: size/s

#63 D8CORE-3246 D8CORE-3487: fixing the external link icons
  dist/css/theme.css
  src/scss/theme/_news.scss
  src/scss/theme/_publications.scss
  src/scss/utilities/mixins/_soe_link-icon.scss
  src/scss/utilities/mixins/index.scss
Labels: size/s

#61 D8CORE-3499: fixing the link icons
  dist/css/theme.css
  src/scss/theme/_publications.scss
Labels: size/xs

#64 D8CORE-3528: updating class name to match reality
  dist/css/theme.css
  src/scss/theme/_super-footer.scss
Labels: size/xs

#65 Update composer.json to use the 5.x branch of stanford_basic
  composer.json
Labels: size/xs
