Repository SU-SOE/soe_basic, pull requests merged in 2021-04, with the labels that each got.

#72 "8.x-1.x 8.1.11
  CHANGELOG.md
  dist/css/theme.css
  soe_basic.info.yml
  src/scss/theme/_news.scss
  src/scss/theme/_publications.scss
  src/scss/theme/_teasers.scss
  src/scss/theme/index.scss
Labels: patch, size/s

#73 Updated components definition in the info.yml
  soe_basic.info.yml
Labels: patch, size/xs

#74 D8CORE-3950: adjusting Past Event list page h1 spacing
  dist/css/theme.css
  src/scss/theme/_background-classes.scss
Labels: size/xs
