Repository SU-SOE/soe_basic, pull requests merged in 2022-03, with the labels that each got.

#92 8.1.19
  CHANGELOG.md
  composer.json
  soe_basic.info.yml
Labels: patch, size/xs

#93 D8CORE-5636: updating css to fix the ext link icon color
  dist/css/theme.css
  src/scss/theme/_hero-banner.scss
Labels: size/xs

#94 8.1.20
  CHANGELOG.md
  composer.json
  dist/css/theme.css
  soe_basic.info.yml
  src/scss/theme/_hero-banner.scss
Labels: patch
